######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 27 23:37:29 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    evgrow.cpp \
    evgwindow.cpp \
    evgmenubar.cpp

HEADERS += \
    evgrow.h \
    evgwindow.h \
    evgmenubar.h

RESOURCES += \
    evgResources.qrc
